// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pb/service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PromptSuggestion_Suggest_FullMethodName = "/PromptSuggestion/Suggest"
)

// PromptSuggestionClient is the client API for PromptSuggestion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PromptSuggestionClient interface {
	Suggest(ctx context.Context, in *SuggestRequest, opts ...grpc.CallOption) (*SuggestResponse, error)
}

type promptSuggestionClient struct {
	cc grpc.ClientConnInterface
}

func NewPromptSuggestionClient(cc grpc.ClientConnInterface) PromptSuggestionClient {
	return &promptSuggestionClient{cc}
}

func (c *promptSuggestionClient) Suggest(ctx context.Context, in *SuggestRequest, opts ...grpc.CallOption) (*SuggestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestResponse)
	err := c.cc.Invoke(ctx, PromptSuggestion_Suggest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromptSuggestionServer is the server API for PromptSuggestion service.
// All implementations must embed UnimplementedPromptSuggestionServer
// for forward compatibility.
type PromptSuggestionServer interface {
	Suggest(context.Context, *SuggestRequest) (*SuggestResponse, error)
	mustEmbedUnimplementedPromptSuggestionServer()
}

// UnimplementedPromptSuggestionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPromptSuggestionServer struct{}

func (UnimplementedPromptSuggestionServer) Suggest(context.Context, *SuggestRequest) (*SuggestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Suggest not implemented")
}
func (UnimplementedPromptSuggestionServer) mustEmbedUnimplementedPromptSuggestionServer() {}
func (UnimplementedPromptSuggestionServer) testEmbeddedByValue()                          {}

// UnsafePromptSuggestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromptSuggestionServer will
// result in compilation errors.
type UnsafePromptSuggestionServer interface {
	mustEmbedUnimplementedPromptSuggestionServer()
}

func RegisterPromptSuggestionServer(s grpc.ServiceRegistrar, srv PromptSuggestionServer) {
	// If the following call pancis, it indicates UnimplementedPromptSuggestionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PromptSuggestion_ServiceDesc, srv)
}

func _PromptSuggestion_Suggest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromptSuggestionServer).Suggest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromptSuggestion_Suggest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromptSuggestionServer).Suggest(ctx, req.(*SuggestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PromptSuggestion_ServiceDesc is the grpc.ServiceDesc for PromptSuggestion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PromptSuggestion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PromptSuggestion",
	HandlerType: (*PromptSuggestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Suggest",
			Handler:    _PromptSuggestion_Suggest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/service.proto",
}
